version: "0.1.0"
volumes:
  data:
    driver: local
services:
  web:
    container_name: web
    restart: always
    build: ./web/
    ports:
      - "4000:3000"
    expose:
      - "3000"
    links:
      - mongo
      - compute
    volumes:
      - data:/data
  compute:
    container_name: compute
    restart: always
    build: ./compute/
    ports:
      - "8080"
    expose:
      - "8080"
    tty: true
    volumes:
      - data:/data
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
