version: "0.1.0"
services:
  app:
    container_name: sitdesign
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
